// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5w07hKQeS-e4w6pA-z3z--utmbqqwss',
    appId: '1:46205037335:web:77a1fb0e38beef42342552',
    messagingSenderId: '46205037335',
    projectId: 'flutter-auth-2934893',
    authDomain: 'flutter-auth-2934893.firebaseapp.com',
    storageBucket: 'flutter-auth-2934893.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbut7nPZhRr_L-YxMlXUvBEqsJyC6Er1E',
    appId: '1:46205037335:android:dc280da14bf34a3e342552',
    messagingSenderId: '46205037335',
    projectId: 'flutter-auth-2934893',
    storageBucket: 'flutter-auth-2934893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5uigCZ-0fD3Qa7L6cnih7Ca0jySai-FE',
    appId: '1:46205037335:ios:79ff679c36d9ff4d342552',
    messagingSenderId: '46205037335',
    projectId: 'flutter-auth-2934893',
    storageBucket: 'flutter-auth-2934893.appspot.com',
    iosBundleId: 'com.example.flutterAuthFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5uigCZ-0fD3Qa7L6cnih7Ca0jySai-FE',
    appId: '1:46205037335:ios:5d0ee560893c3df3342552',
    messagingSenderId: '46205037335',
    projectId: 'flutter-auth-2934893',
    storageBucket: 'flutter-auth-2934893.appspot.com',
    iosBundleId: 'com.example.flutterAuthFinal.RunnerTests',
  );
}
